### ISSUE TITLE
Filter boards to show next depatures from x to y

### ISSUE THREAD

**Issue by ben-fletcher** [benfl3713/DepartureBoard#111]
**Summary**
Allow a user to only show departures from x to y
**Details**
A user should be able to filter departures to only show departures from one station to another. 
This will be done by adding another url configuration **<sitename>/EUS/to/BHM**.
You should still be able to add all other filters such as board count and arrivals
**How to Test**
Test multiple configurations of the url to make sure all url parameters work.

**Comment by benfl3713** [comment]
Done
