### ISSUE TITLE
over seas trains

### ISSUE THREAD

**Issue by qwilpen** [benfl3713/DepartureBoard#161]
could this be adapted to use info from overseas train operators such as Germany (DB)

https://developer.deutschebahn.com/store/apis/list

**Comment by benfl3713** [comment]
Simple answer is yes. I designed it to allow different multiple API sources so I'll see what is possible. I'll comment here with any updates to my findings

**Comment by ben-fletcher** [comment]
I have found this sort of design is common in Germany so I will look to create a new board design to present the German train departures.

**Comment by qwilpen** [comment]
Brilliant thank you so much Ben


Sent from Samsung Mobile on O2

Get Outlook for Android

**Comment by benfl3713** [comment]
I have built the integration with the API you suggested. I have also built a singleboard view of a single departure at a time. Please note that all the UI is in a beta phase. I am now working on another UI that looks like the picture I sent before. 

You can use the singleboard view now by turning on the beta features toggle in settings > general
And then searching in the search box for a german station such as **Aachen Hbf**  

I am happy to take any feedback/improvement to make it any better. Also note that the DB api is still in beta phase so I have only seen it return ICE trains
  
![image](https://user-images.githubusercontent.com/44288013/100464228-260cdd80-30c5-11eb-9a6f-a6ca18f4a02b.png)

**Comment by benfl3713** [comment]
I have built the integration with the API you suggested. I have also built a singleboard view of a single departure at a time. Please note that all the UI is in a beta phase. I am now working on another UI that looks like the picture I sent before. 

You can use the singleboard view now by turning on the beta features toggle in settings > general (You may have to wait for the page to auto refresh in about 10s for the toggle to appear)
And then searching in the search box for a German station such as **Aachen Hbf**  

I am happy to take any feedback/improvement to make it any better. Also note that the DB api is still in beta phase so I have only seen it return ICE trains
  
![image](https://user-images.githubusercontent.com/44288013/100464228-260cdd80-30c5-11eb-9a6f-a6ca18f4a02b.png)

**Comment by benfl3713** [comment]
![](https://fotoeins.files.wordpress.com/2015/01/hl_ffm_0406_ptmodb.jpg?w=910&h=538)
![image](https://user-images.githubusercontent.com/44288013/100466145-5c982780-30c8-11eb-94f2-e5c28e7a3547.png)

**Comment by benfl3713** [comment]
Preview of the main view of many departures for a station
![image](https://user-images.githubusercontent.com/44288013/100483724-cc6ed800-30f1-11eb-8bfb-45c9b79c51e0.png)

**Comment by ben-fletcher** [comment]
# Progress
I am not familiar with German boards so I have currently made it so that if the text is too long then it scrolls across the screen.
I am aware every 30 seconds the scrollers reset and am working on a fix for this to stop them resetting

**Comment by qwilpen** [comment]
looks brilliant to me thanks so much

**Comment by ben-fletcher** [comment]
👍🏻 Seems to be all functioning now and I will roll it out of beta. Feel free to raise any bugs or improvements if you find any 🚝
