### ISSUE TITLE
Speed setting 

### ISSUE THREAD

**Issue by samdarleyeditor** [benfl3713/DepartureBoard#195]
on the single board it would be really useful to change the speed of the scrolling “calling at:” text as it’s too fast for me currently 

amazing website tho, i’ve looked years for something exactly like this!

**Comment by benfl3713** [comment]
I'll take a look at this today, but should be easy to add a setting to control the speed

**Comment by benfl3713** [comment]
Here what the setting will look like, and this will be deployed tonight 

![image](https://user-images.githubusercontent.com/44288013/114937155-54514680-9e35-11eb-84cb-0034773cf379.png)
