### ISSUE TITLE
Search station with dash in name

### ISSUE THREAD

**Issue by ben-fletcher** [benfl3713/DepartureBoard#233]
**Describe the bug**
When you try search for a station with a dash in the name, and select it and click the search button, it fails.

**To Reproduce**
1. Go to home page
2. Click on Search Box
3. Type in `Moreton-in-Marsh - (MIM)` and select it from the box
4. Click search and see error

**Expected behavior**
You should be able to search for a station with a dash in the name

**Additional context**
I believe it is because the search splits the text by dash so it can get the code and name separately

**Comment by benfl3713** [comment]
I have fixed this issue
