### ISSUE TITLE
TfL Tube departures

### ISSUE THREAD

**Issue by joshpople** [benfl3713/DepartureBoard#252]
Hey!
I know that TfL provide APIs for tube departures somewhere as there are physical departure boards you can but, I would love to have a board set up on a spare screen to see my local station to be able to check when my next train is. I’m not sure if the task is hard as I know you have bus stop tracking in the software already.

Thanks in advance

**Comment by benfl3713** [comment]
Hi @joshpople 

Sorry for the delay getting back to you.

Yes tfl do have an api for tubes and it will be fairly easy to integrate with.
Can I confirm it's a board to match the following format found on tube platforms?
https://image.shutterstock.com/image-photo/electronic-departure-time-board-on-260nw-1569221164.jpg

Cheers
Ben

**Comment by benfl3713** [comment]
Hi there @joshpople 

Apologies on delay getting back to you,
Tube departures are available now with a search for your station
https://www.leddepartureboard.com/london-tube/search

Thanks
Ben
