### ISSUE TITLE
Liverpool Street Station (LST) is not returning any departure data

### ISSUE THREAD

**Issue by irishcornelius** [benfl3713/DepartureBoard#263]
**Describe the bug**
National Rail, Liverpool Street Station (LST) is not returning any departure data

**To Reproduce**
1. Go to https://www.leddepartureboard.com/LST
2. No departures showing

**Expected behavior**
Page should show departures matching https://www.realtimetrains.co.uk/search/simple/gb-nr:LST

**Screenshots**
![image](https://user-images.githubusercontent.com/1169980/179486590-8c3bd547-9a55-48ee-a62e-90ed98adfef0.png)

**Comment by benfl3713** [comment]
Hi @irishcornelius thanks for finding this issue. I have taken a look and it looks like that station seems to have a weird quirk with it's data. I am fixing this now
