### ISSUE TITLE
Can't create account/log in with google

### ISSUE THREAD

**Issue by aronhegedus** [benfl3713/DepartureBoard#293]
**Describe the bug**
Cannot create an account on https://admin.leddepartureboard.com/login 
The login screen opens very briefly, then closes

**To Reproduce**
0. On google chrome/safari (macbook pro)
1. Go to https://admin.leddepartureboard.com/login 
2. Click on "sign in with google"
3. Wait, the dialog box will exit.

**Expected behavior**
Should be able to log in using google.

**Comment by aronhegedus** [comment]
https://github.com/benfl3713/DepartureBoard/assets/32208841/da5e1504-dbb1-4826-83a1-c6ecd0dad570

Here's a video

**Comment by benfl3713** [comment]
Hi there @aronhegedus 

Thanks for letting me know about this problem
I think it was a configuration issue with my authentication provider.
I've updated the config to hopefully solve the problem.

Hopefully if you try again now it should work for you

Cheers
Ben
