### ISSUE TITLE
Completely black in iframe on Dakboard Raspberry Pi 4

### ISSUE THREAD

**Issue by webash** [benfl3713/DepartureBoard#301]
**Describe the bug**
An iframe of the London Tube board has been embedded in a Dakboard dashboard which is then being displayed on a Raspberry Pi 4 running DakOS 4.
When showing the Dakboard page, the iframe stays black except for the cookie prompt (or shows nothing at all if cookies are accepted with `?acceptCookies=true`.

In previews on my local browser, the iframe displays as expected.
On the Raspberry Pi's browser, the full webpage (https://www.leddepartureboard.com/london-tube/HUBWSM) displays as expected

**To Reproduce**
1. Go to https://www.leddepartureboard.com/london-tube/HUBWSM
2. Grab the URL and embed in an iframe in Dakboard
3. View the Dakboard on DakOS on Raspberry Pi 4
4. See black box only

**Expected behavior**
The typical departure board should display, like it does on other browsers.

**Screenshots**
Here it is working fine in the preview on my own machine
![image](https://github.com/benfl3713/DepartureBoard/assets/6205899/f6b30fdd-9fed-4863-8cca-fe146947c8e9)
Here it is only being black on the Dakboard / DakOS Raspberry Pi 4
![PXL_20240626_133947615_resize](https://github.com/benfl3713/DepartureBoard/assets/6205899/62c3d218-a90d-4ace-8af0-8f7c4f10d67c)

**Additional context**

**Comment by webash** [comment]
@benfl3713 is there a way that I can force the iframe to load without the custom font?

**Comment by benfl3713** [comment]
Hi @webash Sorry in the delay in getting back to you on this, I've been rather busy with other things so haven't had much time to focus on this project.

I took a look at this iframe issue and found it was throwing errors relating to how websites within iframes have different permissions to normal websites. 

I've made some code changes to address these issues and have just deployed the changes now. You should be able to try it again now and see some results hopefully!

**Comment by webash** [comment]
I thought I was going crazy. I hadn't looked at it since a few days after my post, until yesterday when I setup the Dakboard PC that this is embedded on in our building lobby and saw it was working. Hadn't seen this reply until just now. Yes all working! Thanks for picking this up! Legend!

**Comment by webash** [comment]
iframe now works on Dakboard embed as expected. Closing issue.
