### ISSUE TITLE
Use Sentence / Title case instead of UPPERCASE

### ISSUE THREAD

**Issue by CrispyUK** [benfl3713/DepartureBoard#73]
Switch to using Title Case for station and operator names, and Sentence case for other departure board elements for improved readability and to be consistent with the real-life boards (e.g. https://www.dreamstime.com/editorial-photography-live-departures-board-birmingham-new-street-train-destination-boards-railway-station-england-uk-western-europe-image73262297)

**Comment by benfl3713** [comment]
This is currently a problem with the font I am using at the moment that only allows upper case characters. I'll look around the internet to try find another similar font that supports both cases

**Comment by benfl3713** [comment]
I have found a font now so this will be done
![image](https://user-images.githubusercontent.com/44288013/82479487-63673180-9aca-11ea-9d93-f0e4827f3234.png)
