### ISSUE TITLE
News as Config file

### ISSUE THREAD

**Issue by ben-fletcher** [benfl3713/DepartureBoard#90]
**Summary**
Change the news to be loaded from a json config file
**Details**
Currently the news is hard coded as html. It should now be changed so that the news is loaded from a json file dynamically. This will allow the news to be changed without a code change
**How to Test**
Test different news articles and test invalid formatting

**Comment by ben-fletcher** [comment]
Use s3 bucket with volume mapping for production setup

**Comment by benfl3713** [comment]
Done as separate file so that the news still goes through change control
