### ISSUE TITLE
No config.xml

### ISSUE THREAD

**Issue by michaeldun** [benfl3713/DepartureBoard#92]
I have looked everywhere in your departureboard repo, and I can't find config.xml at all. I have checked everywhere. I shall include a screenshot of where it is meant to be as said in the readme.md.

https://i.imgur.com/qiFvPQ9.png

https://i.imgur.com/l6VwOQe.png

Thank you :)

**Comment by ben-fletcher** [comment]
Hi @michaeldun 
I haven't updated the readme yet, but if you run the application then it should automatically create the config.xml for you. If not then let me know.

It will however be populated with a blank filler where you can input your realtimetrains api token

**Comment by ben-fletcher** [comment]
It should look like this.
<Config><RealTimeTrainsToken>[INSERT_REALTIMETRAINS_TOKEN_HERE]</RealTimeTrainsToken></Config>

**Comment by michaeldun** [comment]
How do I run the solution file?
Thanks

**Comment by ben-fletcher** [comment]
As I see your running visual code then you don't need to worry about the solution file.
To run it you will need node and the dotnet core 3.1 sdk https://dotnet.microsoft.com/download/dotnet-core/3.1
then just run in the DepartureboardWeb folder `dotnet run`

**Comment by michaeldun** [comment]
Alright. Thanks

**Comment by michaeldun** [comment]
@ben-fletcher Just ran it for a while now, and nothing is coming up 
![image](https://user-images.githubusercontent.com/39377683/82047904-87caa480-96ab-11ea-982e-c40203d823ec.png)
Not even in the output or anywhere

**Comment by michaeldun** [comment]
Ooo As I posted that, something happened

**Comment by michaeldun** [comment]
But, still no config.xml 
![image](https://user-images.githubusercontent.com/39377683/82048044-cb251300-96ab-11ea-9341-833f625ba065.png)

**Comment by michaeldun** [comment]
Works now. Thank you!
